import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import ScrollEffects from "@/components/ScrollEffects";
import BackgroundOrbs from "@/components/BackgroundOrbs";

const montserrat = Montserrat({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "KUZAKEN.TECH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased kb-bg`}
      >
        <ThemeProvider>
          <Header />
          <BackgroundOrbs />
          <ScrollEffects />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
